[package]
name = "neosh"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
neosh-proto = { workspace = true }
neosh-core = { workspace = true }
neosh-provider = { workspace = true }
neosh-agent = { workspace = true }
neosh-script = { workspace = true }
neosh-vcs = { workspace = true }
neosh-tui = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
futures = { workspace = true }
clap = { workspace = true }
directories = { workspace = true }
shellexpand = { workspace = true }
sha2 = { workspace = true }
secrecy = { workspace = true }
unicode-segmentation = { workspace = true }
async-trait = { workspace = true }
crossterm = { workspace = true }
url = "2"
tokio-stream = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
serde_json = { workspace = true }
