#!/usr/bin/env bash
#
# Print the Homebrew formula for a published release.
#
#   scripts/brew-formula.sh v0.1.0 > Formula/neosh.rb
#
# Reads the `.sha256` files the release workflow attaches beside each tarball, so this can only be
# run once a release exists — which is the point: a formula with a checksum somebody typed is a
# formula that installs whatever is at that URL now.
#
# The result belongs in neoswarm/homebrew-tap, and is what makes this work:
#
#   brew install neoswarm/tap/neosh
#
# Not homebrew-core: that has notability requirements (roughly 75 stars, 30 forks, 30 watchers) and
# a tap has none, while being the same one-line install to whoever is typing it.
set -euo pipefail

tag="${1:?usage: brew-formula.sh <tag>, e.g. v0.1.0}"
version="${tag#v}"
repo="neoswarm/neosh"
base="https://github.com/$repo/releases/download/$tag"

sha_for() {
  local target="$1" url="$base/neosh-$target.tar.gz.sha256"
  local line
  # The file is `<sha256>  <filename>`, which is what `shasum -a 256` writes.
  line=$(curl -fsSL "$url") || {
    echo "brew-formula.sh: no checksum at $url" >&2
    echo "  (has the release finished building? gh run list --workflow release.yml)" >&2
    exit 1
  }
  printf '%s' "$line" | awk '{print $1}'
}

sha_darwin_arm=$(sha_for aarch64-apple-darwin)
sha_darwin_x86=$(sha_for x86_64-apple-darwin)
sha_linux_x86=$(sha_for x86_64-unknown-linux-gnu)
sha_linux_arm=$(sha_for aarch64-unknown-linux-gnu)

cat <<RUBY
# Generated by scripts/brew-formula.sh in neoswarm/neosh — do not hand-edit.
class Neosh < Formula
  desc "Terminal-first agent workspace where every feature is a plugin"
  homepage "https://github.com/$repo"
  version "$version"
  license "MIT"

  on_macos do
    on_arm do
      url "$base/neosh-aarch64-apple-darwin.tar.gz"
      sha256 "$sha_darwin_arm"
    end
    on_intel do
      url "$base/neosh-x86_64-apple-darwin.tar.gz"
      sha256 "$sha_darwin_x86"
    end
  end

  on_linux do
    on_arm do
      url "$base/neosh-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "$sha_linux_arm"
    end
    on_intel do
      url "$base/neosh-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "$sha_linux_x86"
    end
  end

  def install
    bin.install "neosh"
  end

  test do
    assert_match "neosh #{version}", shell_output("#{bin}/neosh --version")
  end
end
RUBY
